name: Compile C

# Trigger the workflow on push events
on:
  push:
    branches:
      - main  # Change this to your desired branch if needed

# Define the jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get -y install gcc

    - name: Compile C code
      run: |
        gcc -o main main.c

    - name: Run the compiled program
      run: ./main
