name: Compile C 

#on push file we want to compile
on: [push]

#we do gcc on linux ubuntu build
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest

        steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: C compiling instal
    run: sudo apt-get install gcc
    - name: C compiling
    run: gcc -o main.exe main.c 

  
